= Container tools
include::_attributes.adoc[]

A common concern when adopting a new technology is the right tools that should be used in order to leverage the best and efficient way of working to get better results, this is why it should be used tools that are aligned and compliant with https://opencontainers.org/about/overview/[OCI].    

One of the most important changes that has been introduced from Red Hat in containers are tools that do not require root superpowers and it does not depend on a linux daemon, such as Docker, making it more flexible and reachable to a wide range of audience. Buildah, Podman and Skopeo are basic tools that are pretty handy to create, manage and distribute containers and container images aligned to be OCI compatible.

[#tools-buildah-podman]
== Buildah and Podman, the basis

Let’s take a look at to Buildah and Podman tools in deeper:  

https://github.com/containers/buildah[Buildah]: its name comes from the word ‘builder’ pronounced with a Boston accent, a funny story that begins with a simple conversation, as  https://www.redhat.com/en/authors/daniel-walsh[Daniel Wash] Senior Distinguished Engineer at Red Hat states in the article https://www.redhat.com/en/blog/daemon-haunted-container-world-no-longer-introducing-buildah-10[Introducing Buildah 1.0] “**__why can’t we create a simple tool to build them without running a container daemon? The engineers asked me what to call it and I responded: “just call it builder.” The engineers heard my Boston accent and `Buildah` was born__**”. 

Buildah is a command line tool designed to create and build container images. Despite being a tool designed to be OCI compatible, it could create images from a traditional Dockerfile too, which gives flexibility when needed. Buildah is the perfect tool for scripting and pipelines, due to the ability to execute the same commands that a Dockerfile includes. It comes by default as modules in Kubernetes pipelines tools like tekton, which is useful when the lifecycle automation of a Kubernetes application is needed.

https://github.com/containers/podman[Podman]: is a command line tool that its name does not comes from a funny story like buildah, but more like most of the tools, is an abbreviation of ‘Pod Manager’. Is a tool designed to manage and run containers, images and volumes. The podman’s core is based on a golang library called libpod, which is in charge of all actions that the tool could perform. 

Podman project also has a child project called Podman Desktop, which allows the user to leverage all podman bondages from the desktop. In version v0.14 has introduced kind support to install kubernetes clusters for testing purposes. More details could be found on the https://podman-desktop.io/[project website].


__container-tools__ is a group of packages in Fedora/Red Hat like distributions that includes the necessary packages to manage containers, such as: https://github.com/containers/buildah[Buildah], https://github.com/containers/podman[Podman], https://github.com/containers/skopeo[Skopeo], https://github.com/containers/container-selinux[Container-selinux], https://github.com/containernetworking/plugins[Containernetworking-plugins], https://github.com/containers/fuse-overlayfs[Fuse-overlayfs], https://github.com/rootless-containers/slirp4netns[slirp4netns]. Install as follows:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
sudo dnf module install container-tools -y
----	