= Buildah or Dockerfile, which to choose when building images?
include::_attributes.adoc[]

[#image-build-type]
To build container images can be achieved with two approaches based on programming language: 


* https://en.wikipedia.org/wiki/Imperative_programming[Imperative]: It will be focused on executing in the command line step by step all the commands needed to get the final image to be used in the container. This approach is pretty useful when automation is needed and a lot of steps are custom or need to be taken from different sources.

* https://en.wikipedia.org/wiki/Declarative_programming[Declarative]: It will be used as a source of the steps and information that needs to be passed to build the image. This file could be named Dockerfile or Containerfile, depending on the tools that it will be used to create the image. Most of the tools accept Containerfile except Docker.  This approach does not need to know the actual commands that need to be executed in order to add each step to the resultant images. 


[#image-build-declarative]
== Declarative approach for building the image

Let’s start with the declarative approach because it is simpler and is best-known in the community.


Create a directory to build a new fresh image.

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
mkdir -p ~/custom-apline-net/src;cd ~/custom-apline-net
----	

NOTE: Containerfile and Dockerfiles support the same parameters and sintax.

A Containerfile will be used in the below examples. This file will include the instructions or commands to create the container image:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
cat << EOF  > Containerfile
# Alpine-net
# Alpine image with network tools

FROM alpine:latest

MAINTAINER silvinux <silvinux7@gmail.com>

RUN apk --update add bash python3 conntrack-tools coreutils curl drill iperf3 iproute2 iptables iputils ip6tables keepalived net-tools nftables socat ethtool mtr tcpdump busybox-extras && rm -rf /var/cache/apk/*

RUN adduser -D -u 1000 container

USER container

WORKDIR /home/container

RUN echo "Hello Kubernetes, DECLARATIVE"  > index.html

CMD ["python3","-m","http.server","8080"]

EXPOSE 8080
EOF
----	

NOTE: Buildah and Podman support image creation, but buildah will be used in order to demonstrate how to use it when building images with imperative or declarative approaches.

Build the image running below command:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
buildah bud -t alpine-net .
----

The output should be similar to:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
STEP 1: FROM alpine:latest
STEP 2: MAINTAINER silvinux <silvinux7@gmail.com>
STEP 3: RUN apk --update add bash python3 conntrack-tools coreutils curl drill iperf3 iproute2 iptables iputils ip6tables keepalived net-tools nftables socat ethtool mtr tcpdump busybox-extras && rm -rf /var/cache/apk/*
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/57) Installing ncurses-terminfo-base (6.2_p20210109-r0)
(2/57) Installing bash (5.1.0-r0)
...
(56/57) Installing python3 (3.8.8-r0)
(57/57) Installing tcpdump (4.99.0-r0)
Executing busybox-1.32.1-r6.trigger
Executing ca-certificates-20191127-r5.trigger
OK: 72 MiB in 71 packages
STEP 4: RUN adduser -D -u 1000 container
STEP 5: USER container
STEP 6: WORKDIR /home/container
STEP 7: CMD ["/bin/sh"]
STEP 8: COMMIT alpine-net
Getting image source signatures
Copying blob b2d5eeeaba3a skipped: already exists
Copying blob 200e3c5139a6 done
Copying config 0a8e9bd5f9 done
Writing manifest to image destination
Storing signatures
--> 0a8e9bd5f9c
0a8e9bd5f9c7f9aa577d09a2220c7996946f02a5411737eaf819582d9ddab85f
----

Shown above, when you build the container from the Containerfile, each step corresponds to a command declared in the Containerfile. 

Each layer is made up of the file generated by running that command. 

Along with each step, the layer created is represented by its random hashed generated ID.

The buildah bud command creates a new image named alpine-net. To see the new image in local, run the command:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
buildah images
----

The output should be similar to:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
REPOSITORY                                           TAG      IMAGE ID       CREATED         SIZE
localhost/alpine-net                                 latest   0a8e9bd5f9c7   2 minutes ago   70.2 MB
----

Buildah command can inspect the image metadata once it is built, in order to get the information or parameters instructed into the Containerfile as follows:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
buildah inspect localhost/alpine-net |jq '.OCIv1|{author,config,rootfs}'
----

The output should be similar to:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
{
  "author": "silvinux <silvinux7@gmail.com>",
  "config": {
    "User": "container",
    "ExposedPorts": {
      "9090/tcp": {}
    },
    "Env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ],
    "Cmd": [
      "python3",
      "-m",
      "http.server",
      "9090"
    ],
    "WorkingDir": "/home/container",
    "Labels": {
      "io.buildah.version": "1.26.1"
    }
  },
  "rootfs": {
    "type": "layers",
    "diff_ids": [
      "sha256:f1417ff83b319fbdae6dd9cd6d8c9c88002dcd75ecf6ec201c8c6894681cf2b5",
      "sha256:b5fa209e7ff1cbc00ef2364e1864c2be22e4349c0840290a85bc0e8a27f159ef"
    ]
  }
}
----

[#image-build-imperative]
== Imperative approach fot building the image

Now is the turn to demonstrate how to create the same image through the imperative approach. In order to simplify the process, a script has been provided to create and build the image. It should be considered that the ports and name of the image has been changed in order to make both images run at the same time.


**script - buildah-imperative-script.sh**
[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
cat << EOF > buildah-imperative-script.sh
#!/bin/bash

set -x

# Make sure there is no container start with same name
buildah rm alpine-net-working-container
podman rm alpine-net-imperative -f

# Build minimal image from Alpine
buildah from --name "alpine-net-working-container" alpine:latest

# Install packages needed to execute a python web server and net tools
buildah run alpine-net-working-container -- apk --update add bash python3 conntrack-tools coreutils curl drill iperf3 iproute2 iptables iputils ip6tables keepalived net-tools nftables socat ethtool mtr tcpdump busybox-extras

# Add a user to work with inside the container
buildah run alpine-net-working-container adduser -D -u 1000 container

# Set user to work with inside the container
buildah config --user container alpine-net-working-container

# Set working directory that will be use inside the container
buildah config --workingdir /home/container alpine-net-working-container

# Create a index.html file and copy inside the image
echo "Hello Kubernetes, IMPERATIVE" > index.html
buildah copy alpine-net-working-container index.html /home/container/index.html

# Add the command that must be executed to start the web server in port 9090
buildah config --cmd "python3 -m http.server 9090" alpine-net-working-container

# Expose port 9090
buildah config --port 9090 alpine-net-working-container

# Commit image
buildah commit alpine-net-working-container alpine-net-imperative

# Show local images
buildah images

# run container
# podman run -dit -p9090:9090 --name alpine-net-imperative localhost/alpine-net-imperative
EOF
----	

Execute the script __buildah-imperative-script.sh__ with proper permissions:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
chmod +x buildah-imperative-script.sh;./buildah-imperative-script.sh
----

In order to review the image, buildah inspect will be used to check the new image.

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
buildah inspect localhost/alpine-net-imperative |jq '.OCIv1|{author   master fs}'
----

The output should be similar to:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
{
  "author": null,
  "config": {
    "User": "container",
    "ExposedPorts": {
      "9090": {}
    },
    "Env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ],
    "Cmd": [
      "python3",
      "-m",
      "http.server",
      "9090"
    ],
    "WorkingDir": "/home/container",
    "Labels": {
      "io.buildah.version": "1.26.1"
    }
  },
  "rootfs": {
    "type": "layers",
    "diff_ids": [
      "sha256:f1417ff83b319fbdae6dd9cd6d8c9c88002dcd75ecf6ec201c8c6894681cf2b5",
      "sha256:0a2e865ceabab8661e512c5d61d55ae45c9eb227b95f45019b5666f92fd6a2ff"
    ]
  }
}
----
