= Run a container and verify it works
include::_attributes.adoc[]

The last step would be test the image running the container. As the images where created exposing diferent ports and diferents messages, it should be easy to run two containers at once in the same host. Lest's get out hands dirty.

[#testing-declarative]
== Testing the image building using the declarative approach

For the first approach, port 8080 will be used and the index.html will be populated with the message "Hello Kubernetes, DECLARATIVE". 

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
podman run -dit -p8080:8080 --name alpine-net localhost/alpine-net
----

Once the container is running, it could be checked using the command:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
podman ps -a                                            
----

The output should be similar to:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	                                   
CONTAINER ID  IMAGE                                   COMMAND               CREATED      STATUS      PORTS                   NAMES
77b8ce568080  localhost/alpine-net:latest  python3 -m http.s...  5 hours ago  Created     0.0.0.0:8080->8080/tcp  alpine-net
----

And it could be confirmed that the container is successfully working using the following command:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
curl http://localhost:8080/
----

The output should be:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
Hello Kubernetes, DECLARATIVE
----

[#testing-imperative]
== Testing the image building using the imperative approach

For the second approach, port 9090 will be used and the index.html will be populated with the message "Hello Kubernetes, IMPERATIVE". 

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
podman run -dit -p9090:9090 --name alpine-net-imperative localhost/alpine-net
----

Once the container is running, it could be checked using the command:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
podman ps -a   
----
The output should be similar to:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
CONTAINER ID  IMAGE                                   COMMAND               CREATED      STATUS      PORTS                   NAMES
77b8ce569090 localhost/alpine-net-imperative:latest  python3 -m http.s...  5 hours ago  Created     0.0.0.0:9090->9090/tcp  alpine-net-imperative
----

And it could be confirmed that the container is successfully working using the following command:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
curl http://localhost:9090/
----

The output should be:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
Hello Kubernetes, IMPERATIVE
----